DISABLE:
  - SPELL

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - HTML_DJLINT
  - JAVASCRIPT_STANDARD
  - JSON_NPM_PACKAGE_JSON_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - TYPESCRIPT_STANDARD

FILTER_REGEX_EXCLUDE: (.xcf)$

CSS_STYLELINT_CONFIG_FILE: .stylelintrc.yml
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: .ecrc.json
JSON_JSONLINT_CONFIG_FILE: .jsonlintrc.yml
JSX_ESLINT_CONFIG_FILE: .eslintrc.json
