# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Common
description: Common action logic.
inputs:
  node-version:
    description: Node.js version to use.
    required: true
runs:
  using: composite
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: |
          echo "npm_cache_dir=$(npm config get cache)" >> $GITHUB_ENV
    - name: Cache root node_modules
      id: cache-npm-root
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.npm_cache_dir }}
          ./node_modules
        key: ${{ runner.os }}-node-root-${{ hashFiles('./package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-root-
    - name: Update npm
      run: npm i -g npm
    - name: Install dependencies
      if: ${{ steps.cache-npm-root.outputs.cache-hit != 'true' }}
      shell: bash
      run: npm ci
    - name: Lerna bootstrap
      shell: bash
      run: npx lerna bootstrap
