name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "art/**"
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache root node_modules
        id: cache-npm-root
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ./node_modules
          key: ${{ runner.os }}-node-root-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-root-
      - name: Install dependencies
        if: ${{ steps.cache-npm-root.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Lerna bootstrap
        run: npx lerna bootstrap
      - name: Build
        run: npx lerna run build
      - name: Test
        run: npx lerna run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
