name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "art/**"
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/common
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: npx lerna run build

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        # node-version: [12, 14, 16, 18]
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/common
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: npx lerna run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Find coverage files
        id: coverage-files
        run: |
          LCOV_FILES=$(find packages/ -type f -name "lcov.info" | paste -s -d ',' -)
          echo "::set-output name=list::$LCOV_FILES"
      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.coverage-files.outputs.list }}
